travis:
  secure:
    BINSTAR_TOKEN: oqrytutg5qkZUwKQv0qv+ehTBYgRAKSQYhWhItFC84MLsXyTi9GGoi9aSMaPWoiD5i63J4dic2t0kFjVxN97sluO3ANtMwounfowr2I/cTJ1u9SQIWqT9VoQgsIhNlnFYbyum9E0i3cNWVWgghEkN0YAEvdYd06iSbOqgnBoh5KYyj2zaf2BMNEf0n2fhivH2m5ptvepHtfIpchuUFqGMwKE0uJLJ+BTlCw15KGDbLdehqFLeaKSU55SpzPj+55u9JfjK29kkHHE51QIlYp3+zT2sdDVKg7BnRebGVg9PZrMqWgWtk5NoK8OaRrFehVqv74meXueSzE0zCCSDjxJxnb0cwvSoPDX8UyInUQtnC6Q6uxpE8rWFtSbE4Hgdud226LHvbnwUHxiX2CyNNE3R2pMZhTWRE88l4kP91gnEDtccUhUU/IoTKjCfdieAeVKxka/FzW15gMCAL6L3SiHfDbvcSGP/sJYNTkPhFk+1stGvKoqODbyC+gCoTAf83wYzbCZKyktfDWYr3tanpHEFxjrbOIaP8CKY/P/J3WJcHq/knAC/q8qFZBrKOlZR1xDxmoyKCXo6m6o2rARSEkYDbAlHkW/7SVmss/PC9vAhaNZanvk7lhGUagp0AEhPOzMDUsXt7smiN0pykanDrYbfYS9JsFrw5AsmOmx6m9I3zE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
